/**
 * Generated by `pnpm gen:facade` — do not edit.
 *
 * The `maxim serve` contract these types were generated from. Compared
 * against a live backend's /api/identity.contract_version so a UI built for a
 * different API than the server speaks says so, loudly.
 */
export const CONTRACT_VERSION = '0.2.0'
