/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/diagnose": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Environment diagnostics */
        get: operations["get_diagnose_api_diagnose_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/envelope": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** WS event envelope shape (type-gen only; live stream is /ws) */
        get: operations["get_event_envelope_api_events_envelope_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List LLM profiles */
        get: operations["get_models_api_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/probe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Test a mesh/cloud connection */
        post: operations["post_probe_api_probe_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recall": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** What Maxim remembers about you */
        get: operations["get_recall_api_recall_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run a mode (talk/adventure/sim/rest) */
        post: operations["post_run_api_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/setup/cloud": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Write cloud provider config */
        post: operations["post_setup_cloud_api_setup_cloud_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/setup/mesh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Write mesh (peer→leader) config */
        post: operations["post_setup_mesh_api_setup_mesh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CloudSetupRequest */
        CloudSetupRequest: {
            /** Api Key */
            api_key: string;
            /** Monthly Budget Usd */
            monthly_budget_usd?: number | null;
            /** Profile */
            profile: string;
            /** Provider */
            provider: string;
        };
        /** ConsoleEvent */
        ConsoleEvent: {
            /** Agent Id */
            agent_id?: string | null;
            /** Data */
            data?: {
                [key: string]: unknown;
            };
            /** Kind */
            kind: string;
            /** Ts */
            ts: number;
        };
        /** DiagnoseResponse */
        DiagnoseResponse: {
            /** Platform */
            platform: string;
            /** Sections */
            sections?: components["schemas"]["DiagnoseSection"][];
        };
        /** DiagnoseSection */
        DiagnoseSection: {
            /** Detail */
            detail?: string | null;
            /** Extra */
            extra?: {
                [key: string]: unknown;
            };
            /** Name */
            name: string;
            /**
             * Status
             * @default
             */
            status: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MeshSetupRequest */
        MeshSetupRequest: {
            /** Api Key */
            api_key: string;
            /** Leader Url */
            leader_url: string;
        };
        /** ModelInfoWire */
        ModelInfoWire: {
            /** Api Key Env */
            api_key_env?: string | null;
            /** Backend */
            backend: string;
            /** Cloud */
            cloud: boolean;
            /** Context Length */
            context_length?: number | null;
            /**
             * Downloaded
             * @default false
             */
            downloaded: boolean;
            /** Name */
            name: string;
            /**
             * Ready
             * @default false
             */
            ready: boolean;
        };
        /** ModelsResponse */
        ModelsResponse: {
            /** Groups */
            groups: {
                [key: string]: components["schemas"]["ModelInfoWire"][];
            };
        };
        /** Preference */
        Preference: {
            /** About */
            about: string;
            /** Learned From */
            learned_from?: string | null;
        };
        /** ProbeRequest */
        ProbeRequest: {
            /** Api Key Ref */
            api_key_ref?: string | null;
            /** Model */
            model?: string | null;
            /** Url */
            url: string;
        };
        /** ProbeResult */
        ProbeResult: {
            /** Fix Hint */
            fix_hint?: string | null;
            /** Latency Ms */
            latency_ms?: number | null;
            /** Message */
            message: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "auth_failed" | "unreachable" | "model_missing" | "error";
        };
        /** RecallResponse */
        RecallResponse: {
            /** Name */
            name?: string | null;
            /** Player Model */
            player_model?: string[];
            /** Preferences */
            preferences?: components["schemas"]["Preference"][];
            /** Story Memories */
            story_memories?: components["schemas"]["StoryMemory"][];
        };
        /** RunAccepted */
        RunAccepted: {
            /** Detail */
            detail?: string | null;
            /** Mode */
            mode: string;
            /** Session Id */
            session_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "started" | "rejected";
        };
        /** RunRequest */
        RunRequest: {
            /** Campaign */
            campaign?: string | null;
            /** Input */
            input?: string | null;
            /**
             * Mode
             * @enum {string}
             */
            mode: "talk" | "adventure" | "sim" | "rest";
        };
        /** SetupResult */
        SetupResult: {
            /** Detail */
            detail: string;
            /** Ok */
            ok: boolean;
            /**
             * Placement
             * @enum {string}
             */
            placement: "mesh" | "cloud";
        };
        /** StoryMemory */
        StoryMemory: {
            /** Salience */
            salience?: number | null;
            /** Summary */
            summary: string;
            /** When */
            when?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_diagnose_api_diagnose_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiagnoseResponse"];
                };
            };
        };
    };
    get_event_envelope_api_events_envelope_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsoleEvent"];
                };
            };
        };
    };
    get_models_api_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelsResponse"];
                };
            };
        };
    };
    post_probe_api_probe_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProbeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProbeResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_recall_api_recall_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecallResponse"];
                };
            };
        };
    };
    post_run_api_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_setup_cloud_api_setup_cloud_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CloudSetupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_setup_mesh_api_setup_mesh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MeshSetupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
